### ISSUE TITLE
Generate API Key for CloudConvert

### ISSUE THREAD

**Issue by manoj-bhaskaran** [manoj-bhaskaran/My-Scripts#34]
Obtain the necessary credentials to use the CloudConvert API.

**Tasks:**
- [x] Sign up for a CloudConvert account if you don't have one.
- [x] Navigate to the API section and generate an API key.
- [x] Store the API key securely for use in your scripts.
