### ISSUE TITLE
Handle File Conversion with CloudConvert API

### ISSUE THREAD

**Issue by manoj-bhaskaran** [manoj-bhaskaran/My-Scripts#36]
Extend your script to request a conversion from the uploaded image.

**Tasks:**
- [x] Use the CloudConvert API to specify the desired conversion format (e.g., ```.jpg```).
- [x] Implement functionality to check the status of the conversion process.
- [x] Handle any errors or issues that arise during the conversion.

**Comment by manoj-bhaskaran** [comment]
In progress. Completed coding changes.

Received the following error in testing:
```
2025-01-17 09:14:29,337 - ERROR - Unhandled exception: list indices must be integers or slices, not str
```
Need to debug.

**Comment by manoj-bhaskaran** [comment]
Still working through errors. Refer to [List index errors debug](https://chatgpt.com/c/67999932-8908-8005-afd9-1dd3539ff852)
