### ISSUE TITLE
Write Basic Script to Create a Batch Job

### ISSUE THREAD

**Issue by manoj-bhaskaran** [manoj-bhaskaran/My-Scripts#38]
Write a script to create a batch job that includes uploading images, converting them, and downloading the results.

**Tasks:**
- [ ] Set up your development environment (install any necessary libraries, e.g., ```requests``` for Python).
- [ ] Write a script to authenticate with the CloudConvert API using your API key.
- [ ] Implement functionality to create a job that includes uploading images.
