### ISSUE TITLE
Documentation of the FileDistributor scripts

### ISSUE THREAD

**Issue by manoj-bhaskaran** [manoj-bhaskaran/My-Scripts#44]
Document the entire process, including setup instructions and usage guidelines.
Refactor for efficiency, correctness, robustness, and maintainability.

**Tasks:**
- [x] Refactor for efficiency, correctness, robustness, and maintainability.
- [x] Document setup and configuration for each script.
- [x] Provide usage instructions for each script.
- [x] Include troubleshooting tips and FAQs.
